### PR TITLE
Add a mark-all-like-this function

### PR DESCRIPTION
**Pull request by paradoxxxzero**

### CODE REVIEW

**Comment by magnars** [comment]
Hey, thanks for contributing. I've been wanting this one. A couple issues:
- mark-all-like-this creates a mirror on top of the master region. I'm not sure if this is a problem?
- I wish I could mark a couple instances with mark-more-like-this, and then change my mind and just mark-all-like-this

I'm open to merging now, and take a look at those tweaks myself. But if you want to have a go at it, please do. :-)

**Comment by paradoxxxzero** [comment]
Thanks for the quick reply I will try to address these issues.
In the mean time I tried to create the following function and for a reason I don't understand it does not work:

``` lisp
    (defun mark-all-like-this-in-region (reg-start reg-end)
      "Find and mark all the parts in the region matching the given search"
      (interactive "r")
      (let ((search (read-from-minibuffer "Mark all in region: "))
            (case-fold-search nil))
        (deactivate-mark)
        (save-excursion
          (goto-char reg-start)
          (while (search-forward search reg-end t)
            (mm/create-master-or-mirror (- (point) (length search)) (point))))))
```

Apprently creating master after `search-forward` call makes everything go wrong...
If you have any ideas.

**Comment by paradoxxxzero** [comment]
Here you go

**Comment by magnars** [comment]
Excellent, thanks! :-)

I'll give `mark-all-like-this-in-region` a stab after work today.

**Comment by magnars** [comment]
The reason the above version of `mark-all-like-this-in-region` didn't work, is that the cursor was outside of the master overlay at the end. This is one of the conditions where mark-multiple will clear all. Going to `mm/master-start` at the end resolved the issue.

**Comment by paradoxxxzero** [comment]
Nice, didn't think about that. Thanks for the add in README!

**Comment by magnars** [comment]
Thanks for contributing!

**Pull request merged**
